ALTER TABLE users
    ADD COLUMN IF NOT EXISTS experience_years INTEGER DEFAULT 0;

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS role_title VARCHAR(255);

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS company VARCHAR(255);

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS location VARCHAR(255);

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS linkedin_url VARCHAR(500);

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS github_url VARCHAR(500);